---
title: "git_01"
author: "Mitzy Contreras"
date: "September 16, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Little Birds are dining  
Warily and well,  
Hid in mossy cell:  
Hid, I say, by waiters  
Gorgeous in their gaiters -  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->Some say the world will end in fire,  
Some say in ice.  
From what I've tasted of desire  
I hold with those who favor fire.  
But if it had to perish twice,  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
At midnight, in the month of June,  
I stand beneath the mystic moon.  
An opiate vapor, dewy, dim,  
Exhales from out her golden rim,  
And softly dripping, drop by drop,  
Upon the quiet mountain top,  
Steals drowsily and musically  
Into the universal valley.  
The rosemary nods upon the grave;  
The lily lolls upon the wave;  
Wrapping the fog about its breast,  
The ruin moulders into rest;  
Looking like Lethe, see! the lake  
A conscious slumber seems to take,  
And would not, for the world, awake.  
All Beauty sleeps!—and lo! where lies  
Irene, with her Destinies!  

Oh, lady bright! can it be right—  
This window open to the night?  
The wanton airs, from the tree-top,  